### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by Arktius** [adl1995/generalised-hough-transform#2]
In 'build_reference_table.py' is an indentation error. But even after fixing this and the index error in match_table: 'acc[int(vector[0]+x), int(vector[1]+y)]+=1' as well as in the demo file [rstart = int(..),red,cstart,cend] index has to be integer, the programm doesn't find the right boxes. 
![error_wrong_boxes](https://user-images.githubusercontent.com/31614164/52475507-f9a86a00-2b9b-11e9-8b86-78add0e0c328.PNG)

**Comment by adl1995** [comment]
Thanks for opening the issue.

I've tried reproducing this on my end and the incorrect matching only happens when using Python 3. On Python 2.7 the results obtained are the same as provided in the `README.md` file.

The indentation and index errors have been resolved. I will close this issue and open a separate one for porting the scripts to Python 3.

Feel free to reopen this if you still get incorrect results.
